### PR TITLE
Fix broken package.json.

### PR DESCRIPTION
**Pull request by martindale**
I'm still not sure why, but the `package.json` for this file didn't work until I regenerated it using `npm`.  This has the unfortunate byproduct of removing a few fields, but I'm sure they can be re-added by someone more adept than myself with the format.

**edit:** aha!  Found it!

### CODE REVIEW

**Comment by joeatwork** [comment]
Thanks for submitting this! I can't quite tell what changed here- could you let me know what's different?

**Comment by martindale** [comment]
@joeatwork there was a trailing comma on one of the contributors, which is invalid JSON.  The reasons the diff doesn't show it is because it's reduced to 2-space formatting -- would you like me to restore 4-space?

**Comment by joeatwork** [comment]
I think I see the comma (at line 18) - I can fix this myself. Thank you so much!

**Comment by joeatwork** [comment]
I believe I've fixed this issue in commit 5fcfbe495400f0455705ed - thanks again for your help!

**Comment by raylu** [comment]
for future reference, https://github.com/mixpanel/mixpanel-node/pull/3/files?w=1

**Comment by joeatwork** [comment]
Thanks, @raylu !

**Pull request closed without merging**
